function build_simulink_model()
% BUILD_SIMULINK_MODEL Simulink版 倒立振子制御モデルをプログラム的に構築
%   InvertedPendulum_Simulink.slx を自動生成する

    modelName = 'InvertedPendulum_Simulink';
    scriptDir = fileparts(mfilename('fullpath'));
    rootDir   = fileparts(scriptDir);
    addpath(fullfile(rootDir, 'plant'));
    p = params();

    % 既存モデルを閉じる
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end

    % 新規モデル作成
    new_system(modelName);
    open_system(modelName);

    % ソルバ設定
    set_param(modelName, ...
        'Solver',       'ode45', ...
        'StopTime',     '10', ...
        'MaxStep',      '0.01', ...
        'RelTol',       '1e-6', ...
        'SaveTime',     'on', ...
        'TimeSaveName', 'tout', ...
        'SaveOutput',   'on');

    % ==========================================================
    %  レイアウト概要（左→右フロー、フィードバックは上下を回る）
    %
    %      ┌─────────── u (上ルート) ────────────────────────┐
    %      │                                                  │
    %      ▼                                                  │
    %   [Plant]──→[Integrator]──→[Demux]══[Mux]──→[LQR  ]──→[Switch]──→[Scope]
    %      ▲                        │        ├──→[PID  ]──↗     │       [WS_u]
    %      │                        ↓        ↓                  │
    %      │                    [Scope]   [WS_x]                │
    %      └─────────── x (下ルート) ───────────────────────────┘
    % ==========================================================

    ar = {'autorouting', 'on'};   % 全配線で直角ルーティング

    % ===== ブロック配置 =====

    % --- Plant (MATLAB Function) ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [modelName '/Plant'], ...
        'Position', [100, 177, 260, 223]);

    set_plant_function(modelName, 'Plant', get_plant_code(p));

    % --- Integrator ---
    add_block('simulink/Continuous/Integrator', ...
        [modelName '/Integrator'], ...
        'Position', [380, 185, 450, 215], ...
        'InitialCondition', 'x0');

    % --- Demux (4状態分離) ---
    add_block('simulink/Signal Routing/Demux', ...
        [modelName '/Demux'], ...
        'Position', [560, 148, 567, 252], ...
        'Outputs', '4');

    % --- Mux (状態再結合) ---
    add_block('simulink/Signal Routing/Mux', ...
        [modelName '/Mux_state'], ...
        'Position', [650, 148, 657, 252], ...
        'Inputs', '4');

    % --- LQR Gain (上段 y≈130) ---
    add_block('simulink/Math Operations/Gain', ...
        [modelName '/LQR_Gain'], ...
        'Position', [790, 107, 910, 153], ...
        'Gain', '(-K_lqr)', ...
        'Multiplication', 'Matrix(K*u)');

    % --- PID Subsystem (下段 y≈280) ---
    build_pid_subsystem(modelName, [790, 257, 950, 303]);

    % --- Manual Switch (中央 y=200) ---
    add_block('simulink/Signal Routing/Manual Switch', ...
        [modelName '/Controller_Switch'], ...
        'Position', [1070, 175, 1130, 225]);

    % --- State Scope (Demux下方) ---
    add_block('simulink/Sinks/Scope', ...
        [modelName '/State_Scope'], ...
        'Position', [560, 390, 610, 430], ...
        'NumInputPorts', '4');

    % --- To Workspace x (Mux下方) ---
    add_block('simulink/Sinks/To Workspace', ...
        [modelName '/To_WS_x'], ...
        'Position', [650, 390, 750, 420], ...
        'VariableName', 'x_out', ...
        'SaveFormat', 'Array');

    % --- Control Scope (Switch右) ---
    add_block('simulink/Sinks/Scope', ...
        [modelName '/Control_Scope'], ...
        'Position', [1250, 178, 1300, 218]);

    % --- To Workspace u (Switch右下) ---
    add_block('simulink/Sinks/To Workspace', ...
        [modelName '/To_WS_u'], ...
        'Position', [1250, 248, 1350, 278], ...
        'VariableName', 'u_out', ...
        'SaveFormat', 'Array');

    % ===== 配線（全て autorouting で直角ルーティング） =====

    % 順方向パス
    add_line(modelName, 'Plant/1', 'Integrator/1', ar{:});
    add_line(modelName, 'Integrator/1', 'Demux/1', ar{:});
    for i = 1:4
        add_line(modelName, ['Demux/' num2str(i)], ['Mux_state/' num2str(i)], ar{:});
    end

    % コントローラ分岐
    add_line(modelName, 'Mux_state/1', 'LQR_Gain/1', ar{:});
    add_line(modelName, 'Mux_state/1', 'PID_Subsystem/1', ar{:});
    add_line(modelName, 'LQR_Gain/1', 'Controller_Switch/1', ar{:});
    add_line(modelName, 'PID_Subsystem/1', 'Controller_Switch/2', ar{:});

    % フィードバック（u: Switch→Plant, x: Mux→Plant）
    add_line(modelName, 'Controller_Switch/1', 'Plant/1', ar{:});
    add_line(modelName, 'Mux_state/1', 'Plant/2', ar{:});

    % シンク（状態量）
    for i = 1:4
        add_line(modelName, ['Demux/' num2str(i)], ['State_Scope/' num2str(i)], ar{:});
    end
    add_line(modelName, 'Mux_state/1', 'To_WS_x/1', ar{:});

    % シンク（制御入力）
    add_line(modelName, 'Controller_Switch/1', 'Control_Scope/1', ar{:});
    add_line(modelName, 'Controller_Switch/1', 'To_WS_u/1', ar{:});

    % 保存（スクリプトと同じディレクトリに .slx を配置）
    slxPath = fullfile(scriptDir, modelName);
    save_system(modelName, slxPath);
    fprintf('モデル "%s.slx" を生成しました。\n', slxPath);
end


function build_pid_subsystem(modelName, pos)
% PID Subsystem を構築（角度PID + 位置PID の合算）

    subName = [modelName '/PID_Subsystem'];
    add_block('simulink/Ports & Subsystems/Subsystem', subName, ...
        'Position', pos);

    % デフォルトの In1->Out1 ラインを削除
    delete_line(subName, 'In1/1', 'Out1/1');

    ar = {'autorouting', 'on'};

    % In/Out ポート位置を調整
    set_param([subName '/In1'],  'Position', [30, 88, 60, 102]);
    set_param([subName '/Out1'], 'Position', [560, 83, 590, 97]);

    % Demux (4状態分離)
    add_block('simulink/Signal Routing/Demux', ...
        [subName '/Demux_pid'], ...
        'Position', [110, 30, 117, 170], ...
        'Outputs', '4');
    add_line(subName, 'In1/1', 'Demux_pid/1', ar{:});

    % 角度PID (Demux port 3: theta)
    add_block('simulink/Continuous/PID Controller', ...
        [subName '/Angle_PID'], ...
        'Position', [220, 18, 370, 58], ...
        'P', '50', 'I', '5', 'D', '15', ...
        'N', '100');
    add_line(subName, 'Demux_pid/3', 'Angle_PID/1', ar{:});

    % 位置PID (Demux port 1: x)
    add_block('simulink/Continuous/PID Controller', ...
        [subName '/Position_PID'], ...
        'Position', [220, 128, 370, 168], ...
        'P', '10', 'I', '0.5', 'D', '15', ...
        'N', '100');
    add_line(subName, 'Demux_pid/1', 'Position_PID/1', ar{:});

    % Sum (角度PID + 位置PID → u)
    add_block('simulink/Math Operations/Add', ...
        [subName '/Sum_PID'], ...
        'Position', [460, 70, 500, 110]);
    add_line(subName, 'Angle_PID/1', 'Sum_PID/1', ar{:});
    add_line(subName, 'Position_PID/1', 'Sum_PID/2', ar{:});

    % Sum → Out1
    add_line(subName, 'Sum_PID/1', 'Out1/1', ar{:});
end


function code = get_plant_code(p)
% MATLAB Function ブロック用のコードを返す
    code = [...
        'function dxdt = plant_fcn(u, x_state)' newline ...
        '%#codegen' newline ...
        '% 台車型倒立振子の非線形運動方程式' newline ...
        '% 状態: x_state = [x; x_dot; theta; theta_dot]' newline ...
        '% 入力: u = F (台車への水平力)' newline ...
        '' newline ...
        'dxdt = zeros(4,1);' newline ...
        '' newline ...
        '% params.m に合わせた簡略プラントのパラメータ' newline ...
        sprintf('M = %.15g;    %% 台車質量 [kg]\\n', p.M) ...
        sprintf('m = %.15g;    %% 振子質量 [kg]\\n', p.m) ...
        sprintf('l = %.15g;    %% 振子長さ [m]\\n', p.l) ...
        sprintf('g = %.15g;    %% 重力加速度 [m/s^2]\\n', p.g) ...
        sprintf('b = %.15g;    %% 台車方向粘性摩擦 [N*s/m]\\n', p.bx) ...
        '' newline ...
        'x_dot   = x_state(2);' newline ...
        'theta   = x_state(3);' newline ...
        'th_dot  = x_state(4);' newline ...
        'F       = u;' newline ...
        '' newline ...
        'sin_th = sin(theta);' newline ...
        'cos_th = cos(theta);' newline ...
        '' newline ...
        'D = M + m - m * cos_th^2;' newline ...
        '' newline ...
        'x_ddot  = (F - b*x_dot + m*l*th_dot^2*sin_th - m*g*sin_th*cos_th) / D;' newline ...
        'th_ddot = ((M+m)*g*sin_th - cos_th*(F - b*x_dot + m*l*th_dot^2*sin_th)) / (l*D);' newline ...
        '' newline ...
        'dxdt = [x_dot; x_ddot; th_dot; th_ddot];' newline ...
        'end' newline];
end


function set_plant_function(modelName, blockName, code)
% MATLAB Function ブロックのスクリプトを設定する
    blockPath = [modelName '/' blockName];
    root = sfroot;
    chart = find(root, '-isa', 'Stateflow.EMChart', 'Path', blockPath);
    if ~isempty(chart)
        chart.Script = code;
    else
        warning('MATLAB Function ブロック "%s" が見つかりません。手動でコードを設定してください。', blockPath);
    end
end
