function mrac = design_mrac(p, nominal_q, nominal_r, lyapunov_q)
% DESIGN_MRAC LQR-anchored MRAC parameters for the force-input plant.
%   Plant:           x_dot = A x + B u
%   State:           x = [position; velocity; theta; theta_dot]
%   Feature vector:  phi = [x; 1]
%   Reference model: x_m_dot = A_m x_m
%   Control:         u = -(Kx * x + Theta_hat' * phi)
%   Adaptation:      Theta_hat_dot = Gamma * phi * (e' * P * B) / (eps + phi' * phi) - sigma * Theta_hat
%   where e = x - x_m

    [A, B, ~, ~] = linearize_system(p);

    if nargin < 2 || isempty(nominal_q)
        nominal_q = diag([100, 0, 50, 100]);
    end

    if nargin < 3 || isempty(nominal_r)
        nominal_r = 10.0;
    end

    if nargin < 4 || isempty(lyapunov_q)
        lyapunov_q = diag([12, 1.5, 30, 6]);
    end

    Kx = lqr(A, B, nominal_q, nominal_r);
    Am = A - B * Kx;
    P = lyap(Am', lyapunov_q);

    mrac = struct( ...
        'NominalQ', nominal_q, ...
        'NominalR', nominal_r, ...
        'Q', lyapunov_q, ...
        'Kx', Kx, ...
        'Am', Am, ...
        'P', P, ...
        'PB', P * B, ...
        'GammaDiag', diag([0.035, 0.006, 0.12, 0.012, 0.08]), ...
        'Sigma', 2.0, ...
        'NormalizationEps', 0.10, ...
        'AdaptationDelaySec', 0.75, ...
        'ErrorDeadzone', 0.002, ...
        'MaxAdaptiveGain', 1.5, ...
        'MaxAdaptiveForce', 1.5, ...
        'EnableAngleLimit', deg2rad(10), ...
        'EnableAngularVelocityLimit', 3.5, ...
        'EnablePositionLimit', 0.35, ...
        'EnableVelocityLimit', 1.2);
end
