function mrac = design_mrac(p, nominal_q, nominal_r, lyapunov_q)
% DESIGN_MRAC Direct MRAC parameters for the mode4 augmented voltage plant.
%   Plant:           x_dot = A x + B v
%   State:           x = [position; velocity; theta; theta_dot; current]
%   Reference model: x_m_dot = A_m x_m
%   Control:         v = -(Kx + Theta_hat)' * x
%   Adaptation:      Theta_hat_dot = Gamma * x * (e' * P * B) / (eps + x' * x) - sigma * Theta_hat
%   where e = x - x_m

    [A, B, ~, ~] = linearize_mode4_voltage_system(p);

    if nargin < 2 || isempty(nominal_q)
        nominal_q = diag([20, 0.5, 800, 20, 0.2]);
    end

    if nargin < 3 || isempty(nominal_r)
        nominal_r = 0.75;
    end

    if nargin < 4 || isempty(lyapunov_q)
        lyapunov_q = diag([18, 1.5, 90, 5, 0.03]);
    end

    Kx = lqr(A, B, nominal_q, nominal_r);
    Am = A - B * Kx;
    P = lyap(Am', lyapunov_q);

    mrac = struct( ...
        'NominalQ', nominal_q, ...
        'NominalR', nominal_r, ...
        'Q', lyapunov_q, ...
        'Kx', Kx, ...
        'Am', Am, ...
        'P', P, ...
        'PB', P * B, ...
        'GammaDiag', diag([0.024, 0.008, 0.12, 0.016, 0.0016]), ...
        'Sigma', 5.0, ...
        'NormalizationEps', 0.35, ...
        'MaxVoltage', 9.0, ...
        'MaxVoltageSlewRate', 150.0, ...
        'AdaptationDelaySec', 0.50, ...
        'ErrorDeadzone', 0.03, ...
        'MinActiveVoltage', 0.10, ...
        'MinDriveVoltage', 0.50, ...
        'LowSpeedVelocityThreshold', 0.02, ...
        'StictionEnableAngleLimit', deg2rad(2.5), ...
        'StictionEnableAngularVelocityLimit', 1.2, ...
        'ThetaFilterCutoff', 50.0, ...
        'ThetaDotFilterCutoff', 25.0, ...
        'ThetaSoftZone', deg2rad(1.2), ...
        'ThetaDotSoftZone', deg2rad(12.0), ...
        'InnerAngleGain', 1.0, ...
        'InnerAngularVelocityGain', 0.40, ...
        'CurrentSoftZone', 0.20, ...
        'InnerCurrentGain', 0.35, ...
        'UseCurrentEstimate', true, ...
        'MaxAdaptiveGain', 2.0, ...
        'EnableAngleLimit', deg2rad(15), ...
        'EnableAngularVelocityLimit', 6.0, ...
        'EnableCurrentLimit', 1.2);
end
