function obs = design_observer(A, B, C, Ts, continuous_poles)
% DESIGN_OBSERVER Discrete-time Luenberger observer for firmware.
%   State:  x = [x; x_dot; theta; theta_dot]
%   Input:  u = F
%   Output: y = [x; theta]

    if nargin < 4 || isempty(Ts)
        Ts = 1e-3; % 1 kHz balance loop
    end

    if nargin < 5 || isempty(continuous_poles)
        continuous_poles = [-25, -30, -35, -40];
    end

    D = zeros(size(C, 1), size(B, 2));
    sysd = c2d(ss(A, B, C, D), Ts, 'zoh');

    discrete_poles = exp(continuous_poles * Ts);
    Ld = place(sysd.A', sysd.C', discrete_poles)';

    obs = struct( ...
        'Ts', Ts, ...
        'A', A, ...
        'B', B, ...
        'C', C, ...
        'Ad', sysd.A, ...
        'Bd', sysd.B, ...
        'Cd', sysd.C, ...
        'Dd', sysd.D, ...
        'continuous_poles', continuous_poles(:), ...
        'discrete_poles', discrete_poles(:), ...
        'Ld', Ld);
end
