function export_mpc_rust(A, B)
% EXPORT_MPC_RUST MPC定数をRust形式で出力
%   design_mpc()の結果をRustのconst配列として表示する

    if nargin < 2
        p = params();
        [A, B, ~, ~] = linearize_system(p);
    end

    mpc = design_mpc(A, B);

    fprintf('#![allow(clippy::excessive_precision)]\n');
    fprintf('// Generated by MATLAB/control/export_mpc_rust.m\n');
    fprintf('// Q = diag([%.0f, %.0f, %.0f, %.0f]), R = %.0f, N = %d, Ts = %.3fs\n\n', ...
        mpc.Q(1,1), mpc.Q(2,2), mpc.Q(3,3), mpc.Q(4,4), mpc.R, mpc.N, mpc.Ts);

    fprintf('pub const MPC_N: usize = %d;\n', mpc.N);
    fprintf('pub const MPC_NX: usize = %d;\n', mpc.nx);
    fprintf('pub const MPC_RHO: f32 = %.1f;\n', mpc.rho);
    fprintf('pub const MPC_MAX_ITER: usize = %d;\n', mpc.max_iter);
    fprintf('pub const MPC_U_MIN: f32 = %.1f;\n', mpc.u_min);
    fprintf('pub const MPC_U_MAX: f32 = %.1f;\n\n', mpc.u_max);

    print_matrix('MPC_H_INV_RHO', '(H + rho*I)^{-1} matrix', mpc.H_inv_rho);
    fprintf('\n');
    print_matrix('MPC_F', 'Gradient coefficient matrix F (f = F * x_current)', mpc.F);
end

function print_matrix(name, desc, M)
    [rows, cols] = size(M);
    fprintf('/// %s, row-major [%d x %d]\n', desc, rows, cols);
    fprintf('#[rustfmt::skip]\n');
    fprintf('pub const %s: [f32; %d] = [\n', name, rows * cols);
    for i = 1:rows
        fprintf('    ');
        for j = 1:cols
            fprintf('%.7e', M(i,j));
            if i == rows && j == cols
                fprintf(',\n');
            else
                fprintf(', ');
            end
        end
        fprintf('\n');
    end
    fprintf('];\n');
end
