function opt = sim_options()
% SIM_OPTIONS Default options and controller parameter factories.
%   Usage: opt = sim_options();
%          opts = opt.default_options(overrides);
%          ctrl = opt.default_controller_param(p, spec);

    opt.default_options = @default_options;
    opt.default_controller_param = @default_controller_param;
end

function opts = default_options(options)
    util = sim_utils();
    if nargin < 1
        options = struct();
    end

    if isfield(options, 'observer')
        observer_cfg = options.observer;
    else
        % オブザーバ行列は必要なときだけ動的に計算
        p = params();
        [A_lin, B_lin, C_lin, ~] = linearize_system(p);
        obs = design_observer(A_lin, B_lin, C_lin);
        observer_cfg = struct( ...
            'Ad', obs.Ad, ...
            'Bd', obs.Bd, ...
            'Ld', obs.Ld);
    end

    opts = struct( ...
        'vin', 12.0, ...
        'current_loop_frequency', 5000.0, ...
        'balance_loop_frequency', 1000.0, ...
        'enable_encoder_quantization', true, ...
        'enable_theta_quantization', true, ...
        'enable_motor_electrical_dynamics', true, ...
        'enable_force_saturation', false, ...
        'force_limit', 10.0, ...
        'max_force', 10.0, ...
        'max_voltage', 12.0, ...
        'theta_filter_cutoff', 50.0, ...
        'theta_dot_filter_cutoff', 25.0, ...
        'current_filter_cutoff', 500.0, ...
        'current_pid', struct( ...
            'Kp', 0.928, ...
            'Ki', 10178.8, ...
            'Kd', 0.0), ...
        'observer', observer_cfg, ...
        'mpc_observer', [], ...
        'disturbance', []);

    opts = util.merge_structs(opts, options);
end

function ctrl_param = default_controller_param(p, spec)
    switch spec.name
        case 'debug'
            ctrl_param = [];
        case 'pid'
            ctrl_param = design_pid();
        case 'lqr'
            [A, B, ~, ~] = linearize_system(p);
            ctrl_param = design_lqr(A, B);
        case 'mrac'
            ctrl_param = design_mrac(p);
        case 'mpc'
            [A, B, ~, ~] = linearize_system(p);
            ctrl_param = design_mpc(A, B);
        otherwise
            error('sim_options:InvalidMode', 'Unsupported mode: %s', spec.name);
    end
end
